name: '@pluginName@'
version: '@version@'
main: org.yuemi.bingogacha.plugin.BingoGachaPlugin
api-version: '@apiVersion@'
authors: [@authors@]
softdepend: [Vault, PlaceholderAPI]
commands:
  bingo:
    description: Main command for Bingo Gacha
    aliases: [bingogacha, bg]
    permission: bingogacha.use
